spring.application.name=documind-backend
app.environment=${APP_ENVIRONMENT:local}
app.release=${APP_RELEASE:dev}

server.port=8080
management.endpoints.web.exposure.include=health,info

aws.region=${AWS_REGION:us-east-1}
bedrock.knowledge-base-id=${BEDROCK_KNOWLEDGE_BASE_ID}
bedrock.model-arn=${BEDROCK_MODEL_ARN}
